# Docker Compose file
# docker-compose.yml
services:
  frontend:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    # No need to expose port 3000 to the host machine
    # as Nginx will proxy the requests internally
    # ports:
    #   - "3000:3000" 
    depends_on:
      - database
    environment:
      - MONGO_URI=mongodb://database:27017/dashboard-app
      - PORT=3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network
    restart: unless-stopped

  database:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: