# Docker Compose file
# docker-compose.yml
name: 3app #name of the project 
services: #abstract definition of compute resource which can be scaled and replaced independently              
  frontend: #define containers with logical name
    build:  #Build section defines how to create image for the service
      context: .
      dockerfile: nginx/Dockerfile
    ports:    #ports mapping
      - "80:80"
    depends_on: #attribute, you can control the order of service startup and shutdown
      - backend
    networks:
      - loki-net

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "4000:4000" 
    depends_on:
      - database
    environment:
      - MONGO_URI=mongodb://database:27017/dashboard-app
      - PORT=4000
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - loki-net
    restart: unless-stopped

  database:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - loki-net
    restart: unless-stopped

volumes:
  mongo-data: